# Generated by Django 4.0.4 on 2022-06-21 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.IntegerField(null=True)),
                ('nombre_cliente', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.IntegerField(null=True)),
                ('precio_producto', models.IntegerField(null=True)),
                ('nom_producto', models.CharField(max_length=15)),
                ('imagen_p', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='CompraProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_compra', models.IntegerField(null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.cliente')),
                ('producto', models.ManyToManyField(to='tienda.producto')),
            ],
        ),
    ]
