# Generated by Django 4.0.4 on 2022-06-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_remove_producto_imagen_p'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='nombre_cliente',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='cliente',
            name='producto',
            field=models.ManyToManyField(to='tienda.producto'),
        ),
        migrations.DeleteModel(
            name='CompraProductos',
        ),
    ]
