# Generated by Django 4.0.4 on 2022-06-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cantidad',
            field=models.IntegerField(null=True),
        ),
    ]
